server:
  port: 8089

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: kun_spring_client_1
            client-secret: zqz9wGEj7yiAxBxUtEl6xWcAnOwCkTJs
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            client-authentication-method: client_secret_post
        provider:
          keycloak:
            issuer-uri: http://ssokun.com:8080/realms/kun_test_1
            user-info-uri: http://ssokun.com:8080/realms/kun_test_1/protocol/openid-connect/userinfo
            token-uri: http://ssokun.com:8080/realms/kun_test_1/protocol/openid-connect/token
            authorization-uri: http://ssokun.com:8080/realms/kun_test_1/protocol/openid-connect/auth

